const VERSION = '3.0';
const SUPABASE_URL = 'https://wntakzfoprthwggkidyq.supabase.co';
const SUPABASE_KEY = 'sb_publishable_gWu_EQ1J3s0iNjeDeINJwQ_xKy8QgAJ';
const THUNDERFOREST_KEY = 'c0ceacbdeb224697bdedd71af8b20abd';
const IDENTITY_KEY = 'yellowdog.identity';
const BASEMAP_KEY = 'yellowdog.basemap';
const FILTERS_KEY = 'yellowdog.filters';
const DEFAULT_CENTER = [46.762, -87.892];
const DEFAULT_ZOOM = 13;
const OWNER_COLORS = { Tod: '#d95a5a', Curt: '#efb349', Steve: '#4e8fd6' };
const TYPE_DEFAULTS = { note: 'Note', parking: 'Parking', camping: 'Camping', hazard: 'Hazard', stretch: 'Stretch', access: 'Area / Access' };
let currentIdentity = safeStorageGet(IDENTITY_KEY, '');
let currentBasemap = safeStorageGet(BASEMAP_KEY, 'outdoors');
let ownerFilters = safeStorageGetJSON(FILTERS_KEY, { Tod: true, Curt: true, Steve: true });
let pendingLayer = null;
let featureGroups = {};
let map = null;
let drawControl = null;
let supabase = null;
let pollingHandle = null;
let lastHash = '';
const statusBadge = document.getElementById('statusBadge');
const identityModal = document.getElementById('identityModal');
const featureModal = document.getElementById('featureModal');
const settingsModal = document.getElementById('settingsModal');
const identitySelect = document.getElementById('identitySelect');
const featureTypeSelect = document.getElementById('featureType');
const featureTitleInput = document.getElementById('featureTitle');
const featureNoteInput = document.getElementById('featureNote');
function safeStorageGet(key, fallback) { try { const value = localStorage.getItem(key); return value === null ? fallback : value; } catch (error) { console.warn('Storage read failed', key, error); return fallback; } }
function safeStorageSet(key, value) { try { localStorage.setItem(key, value); } catch (error) { console.warn('Storage write failed', key, error); } }
function safeStorageGetJSON(key, fallback) { const raw = safeStorageGet(key, ''); if (!raw) return fallback; try { return JSON.parse(raw); } catch (error) { console.warn('Storage JSON parse failed', key, error); return fallback; } }
function setStatus(message) { statusBadge.style.display = 'block'; statusBadge.textContent = message; }
function setReady() { document.body.classList.add('app-ready'); setTimeout(() => { statusBadge.style.display = 'none'; }, 1600); }
function popupHTML(properties) { const title = escapeHTML(properties.title || TYPE_DEFAULTS[properties.feature_type] || 'Feature'); const owner = escapeHTML(properties.owner || ''); const type = escapeHTML(properties.feature_type || ''); const note = escapeHTML(properties.note || ''); return `<div class="popup-title">${title}</div><div class="popup-meta">${owner} · ${type}</div><div class="popup-note">${note || 'No notes yet.'}</div>`; }
function escapeHTML(value) { return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;'); }
function createOwnerIcon(owner) { return L.divIcon({ className: '', html: `<div class="custom-owner-icon owner-${owner}"></div>`, iconSize: [18, 18], iconAnchor: [9, 9], popupAnchor: [0, -8] }); }
function styleForFeature(feature) { const owner = feature.properties?.owner || 'Tod'; const color = OWNER_COLORS[owner] || '#888888'; return { color, weight: feature.geometry?.type === 'Polygon' ? 3 : 5, fillColor: color, fillOpacity: 0.18 }; }
function basemapLayers() { return { outdoors: L.tileLayer(`https://tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey=${THUNDERFOREST_KEY}`, { maxZoom: 19, attribution: 'Maps © Thunderforest, Data © OpenStreetMap contributors' }), satellite: L.layerGroup([ L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', { maxZoom: 19, attribution: 'Tiles © Esri' }), L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}', { maxZoom: 19, attribution: 'Labels © Esri' }) ]) }; }
function initMap() { setStatus('Loading map…'); const layers = basemapLayers(); map = L.map('map', { zoomControl: true, preferCanvas: true }).setView(DEFAULT_CENTER, DEFAULT_ZOOM); layers[currentBasemap].addTo(map); featureGroups = { Tod: L.featureGroup().addTo(map), Curt: L.featureGroup().addTo(map), Steve: L.featureGroup().addTo(map) }; L.control.scale({ imperial: true, metric: false }).addTo(map); drawControl = new L.Control.Draw({ position: 'topleft', draw: { polyline: { shapeOptions: { color: OWNER_COLORS[currentIdentity || 'Tod'], weight: 5 } }, polygon: { allowIntersection: false, showArea: true, shapeOptions: { color: OWNER_COLORS[currentIdentity || 'Tod'], weight: 3 } }, rectangle: { shapeOptions: { color: OWNER_COLORS[currentIdentity || 'Tod'], weight: 3 } }, circle: false, circlemarker: false, marker: true }, edit: false }); map.addControl(drawControl); document.getElementById('basemapBtn').addEventListener('click', () => { const next = currentBasemap === 'outdoors' ? 'satellite' : 'outdoors'; layers[currentBasemap].remove(); currentBasemap = next; safeStorageSet(BASEMAP_KEY, currentBasemap); layers[currentBasemap].addTo(map); setStatus(`Showing ${currentBasemap} basemap.`); setTimeout(() => { statusBadge.style.display = 'none'; }, 1200); }); document.getElementById('refreshBtn').addEventListener('click', loadFeatures); setReady(); }
function rowToLayer(row) { const owner = row.owner; return L.geoJSON(row.geometry, { pointToLayer: function(feature, latlng) { return L.marker(latlng, { icon: createOwnerIcon(owner) }); }, style: function(feature) { return styleForFeature({ geometry: row.geometry, properties: { owner, feature_type: row.feature_type } }); }, onEachFeature: function(feature, layer) { layer.bindPopup(popupHTML({ owner: row.owner, feature_type: row.feature_type, title: row.title, note: row.note })); } }); }
async function loadFeatures() { setStatus('Loading shared notes…'); const { data, error } = await supabase.from('map_features').select('*').order('created_at', { ascending: true }); if (error) { console.error(error); setStatus(`Supabase read failed: ${error.message}`); return; } const newHash = JSON.stringify(data.map(row => [row.id, row.updated_at])); if (newHash === lastHash) { statusBadge.style.display = 'none'; return; } lastHash = newHash; Object.values(featureGroups).forEach(group => group.clearLayers()); data.forEach(row => { const owner = featureGroups[row.owner] ? row.owner : 'Tod'; featureGroups[owner].addLayer(rowToLayer(row)); }); applyOwnerFilters(); setStatus('Map data updated.'); setTimeout(() => { statusBadge.style.display = 'none'; }, 900); }
function applyOwnerFilters() { Object.keys(featureGroups).forEach(owner => { if (ownerFilters[owner] === false) { if (map.hasLayer(featureGroups[owner])) map.removeLayer(featureGroups[owner]); } else { if (!map.hasLayer(featureGroups[owner])) map.addLayer(featureGroups[owner]); } }); }
function bindIdentityUI() { identitySelect.value = currentIdentity || 'Tod'; document.querySelectorAll('.identityBtn').forEach(btn => { btn.addEventListener('click', () => { currentIdentity = btn.dataset.name; safeStorageSet(IDENTITY_KEY, currentIdentity); identitySelect.value = currentIdentity; identityModal.classList.remove('visible'); }); }); if (!currentIdentity) identityModal.classList.add('visible'); document.getElementById('settingsBtn').addEventListener('click', () => { identitySelect.value = currentIdentity || 'Tod'; settingsModal.classList.add('visible'); }); document.getElementById('saveSettingsBtn').addEventListener('click', () => { currentIdentity = identitySelect.value; safeStorageSet(IDENTITY_KEY, currentIdentity); settingsModal.classList.remove('visible'); }); document.getElementById('closeSettingsBtn').addEventListener('click', () => settingsModal.classList.remove('visible')); }
function bindLayerToggles() { document.querySelectorAll('#legend input[type="checkbox"]').forEach(cb => { cb.checked = ownerFilters[cb.dataset.owner] !== false; cb.addEventListener('change', () => { ownerFilters[cb.dataset.owner] = cb.checked; safeStorageSet(FILTERS_KEY, JSON.stringify(ownerFilters)); applyOwnerFilters(); }); }); }
function guessTypeFromLayer(layer) { if (layer instanceof L.Marker) return 'note'; if (layer instanceof L.Polygon) return 'access'; if (layer instanceof L.Polyline) return 'stretch'; return 'note'; }
function openFeatureModal(layer) { pendingLayer = layer; featureTypeSelect.value = guessTypeFromLayer(layer); featureTitleInput.value = ''; featureNoteInput.value = ''; featureModal.classList.add('visible'); }
function cancelPendingFeature() { if (pendingLayer) { try { map.removeLayer(pendingLayer); } catch (e) {} } pendingLayer = null; featureModal.classList.remove('visible'); }
async function savePendingFeature() { if (!pendingLayer) return; const featureType = featureTypeSelect.value; let geometry = null; if (pendingLayer instanceof L.Marker) { const ll = pendingLayer.getLatLng(); geometry = { type: 'Point', coordinates: [ll.lng, ll.lat] }; } else if (pendingLayer instanceof L.Polygon) { const ring = pendingLayer.getLatLngs()[0].map(ll => [ll.lng, ll.lat]); if (ring.length && (ring[0][0] !== ring[ring.length - 1][0] || ring[0][1] !== ring[ring.length - 1][1])) ring.push([ring[0][0], ring[0][1]]); geometry = { type: 'Polygon', coordinates: [ring] }; } else if (pendingLayer instanceof L.Polyline) { geometry = { type: 'LineString', coordinates: pendingLayer.getLatLngs().map(ll => [ll.lng, ll.lat]) }; } const payload = { owner: currentIdentity || 'Tod', feature_type: featureType, geometry, title: featureTitleInput.value.trim(), note: featureNoteInput.value.trim(), color: OWNER_COLORS[currentIdentity || 'Tod'] }; const { error } = await supabase.from('map_features').insert(payload); if (error) { console.error(error); alert(`Save failed: ${error.message}`); return; } pendingLayer = null; featureModal.classList.remove('visible'); await loadFeatures(); }
function bindFeatureModal() { document.getElementById('cancelFeatureBtn').addEventListener('click', cancelPendingFeature); document.getElementById('saveFeatureBtn').addEventListener('click', savePendingFeature); featureModal.addEventListener('click', (event) => { if (event.target === featureModal) cancelPendingFeature(); }); settingsModal.addEventListener('click', (event) => { if (event.target === settingsModal) settingsModal.classList.remove('visible'); }); identityModal.addEventListener('click', (event) => { if (event.target === identityModal && currentIdentity) identityModal.classList.remove('visible'); }); }
function bindDrawEvents() { map.on(L.Draw.Event.CREATED, function(event) { openFeatureModal(event.layer); }); }
async function startRealtime() { try { supabase.channel('map_features_live_leaflet').on('postgres_changes', { event: '*', schema: 'public', table: 'map_features' }, async () => { await loadFeatures(); }).subscribe(); } catch (error) { console.warn('Realtime subscribe failed, polling will still run.', error); } if (pollingHandle) clearInterval(pollingHandle); pollingHandle = setInterval(loadFeatures, 15000); }
async function startApp() { if (!window.L) throw new Error('Leaflet library did not load.'); if (!window.supabase || !window.supabase.createClient) throw new Error('Supabase library did not load.'); supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY); bindIdentityUI(); bindLayerToggles(); bindFeatureModal(); initMap(); bindDrawEvents(); await loadFeatures(); await startRealtime(); }
startApp().catch(error => { console.error(error); setStatus(`Startup error: ${error.message}`); alert(`Startup error: ${error.message}`); });
